language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
#    - build-tools-28.0.0
    - android-28
    - extra-android-support

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

#  before_install:
#    - chmod +x gradlew
#    - mkdir "$ANDROID_HOME/licenses" || true
#    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
#    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
#    - yes | sdkmanager --update
#    - yes | sdkmanager --licenses
#
#  before_script:
#    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#    - emulator -avd test -no-skin -no-audio -no-window &
#    - android-wait-for-emulator
#    - adb shell input keyevent 82 &
