language: android
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - platform-tools
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
  licenses:
    - '.+'

sudo: required
jdk:
  - oraclejdk8
install:
  - true

script:
  - ./gradlew test --console verbose -i
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

#
# Disabled for now as "git tag $NAME" throws "fatal: too many params"
#
#before_deploy:
#  - ./gradlew clean
#  - ./gradlew :library:createFullJarRelease
#  - ./gradlew :library:bundleReleaseAar
#  - ./gradlew :library:copyJar
#  - export NAME="v$(./gradlew version -q)"
#  - git tag $NAME
#
#deploy:
#  - provider: releases
#    api_key: "$GITHUB_TOKEN_TEMP"
#    file_glob: true
#    file: "attachments/*"
#    skip_cleanup: true
#    name: $NAME
#    on:
#        tags: true
#        branch: feature/jar
