name: Clean Detekt Baseline Files

on:
  schedule:
    # Every midnight
    - cron: "0 0 * * *"

jobs:
  clean_detekt_baseline_files:
    name: Clean Detekt Baseline Files
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          token: ${{ secrets.STREAM_PUBLIC_BOT_TOKEN }}
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: tibdex/github-app-token@v1.7.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID_OBTAIN_TOKEN }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_OBTAIN_TOKEN }}
      - name: Run Detekt Baseline
        run: ./gradlew detektBaseline
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "AUTOMATION: Clean Detekt Baseline Files"
          title: "AUTOMATION: Clean Detekt Baseline Files"
          delete-branch: true
          reviewers: JcMinarro
          assignees: JcMinarro
          body: |
            - Clean Detekt Baseline Files

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: clean-detect-baseline-files
          token: ${{ steps.generate-token.outputs.token }}
