name: Download translations from Localazy

on:
  schedule:
    # Every midnight
    - cron: "0 0 * * *"

jobs:
  localazy-download:
    name: Download strings from Localazy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: GetStream/android-ci-actions/actions/setup-java@main
      - uses: tibdex/github-app-token@v1.7.0
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID_OBTAIN_TOKEN }}
          private_key: ${{ secrets.APP_PRIVATE_KEY_OBTAIN_TOKEN }}
      - uses: localazy/download@v1.1.0
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
      - uses: GetStream/android-ci-actions/actions/gradle-cache@main
        with:
          cache-name: gradle-lint
      - name: Add license headers
        run: ./gradlew spotlessApply
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            commit-message: "AUTOMATION: Update translations"
            title: "AUTOMATION: Update translations"
            delete-branch: true
            reviewers: GetStream/android-developers
            body: |
              - Translations downloaded from Localazy

              Auto-generated by [create-pull-request][1]

              [1]: https://github.com/peter-evans/create-pull-request
            branch: update-translations
            token: ${{ steps.generate-token.outputs.token }}
