name: PR cleanup

on:
  schedule:
    - cron: "0 7 * * 1"  # every Monday 07:00 UTC (08:00 CET / 09:00 CEST)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  pr-clean-stale:
    uses: GetStream/stream-build-conventions-android/.github/workflows/pr-clean-stale.yaml@v0.6.1
    secrets: inherit
