name: PR checklist

on:
  pull_request:
    types: [ opened, edited, synchronize, labeled, unlabeled, reopened ]

permissions:
  contents: read
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-checklist:
    uses: GetStream/stream-build-conventions-android/.github/workflows/pr-quality.yml@v0.7.1
    secrets: inherit
