name: SyncRelease

on:
  workflow_run:
    workflows: ["VersionBump"]
    types:
      - completed

jobs:
  sync_release:
    runs-on: ubuntu-latest
    environment: 'publish'
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Sync main
        run: | 
          git pull
          git merge --ff-only origin/develop
      - name: Create Tag
        run: |
          ./gradlew version-print
          version="$(cat temp-version)"
          echo GITHUB_TAG_VERSION=$version >> $GITHUB_ENV
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git tag -a v$version -m "Release version $version"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      - name: Generate release file
        run: ./gradlew generate-release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          bodyFile: "CHANGELOG_PARSED.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.GITHUB_TAG_VERSION }}


